(define (problem BLOCKS-9-0)
(:domain BLOCKS)
(:objects H - block D - block I - block A - block E - block G - block B - block F - block C - block)
(:INIT ( and (CLEAR C) (CLEAR F) (ONTABLE C) (ONTABLE B) (ON F G) (ON G E) (ON E A)
 (ON A I) (ON I D) (ON D H) (ON H B) (HANDEMPTY)) )
(:goal (AND (ON G D) (ON D B) (ON B C) (ON C A) (ON A I) (ON I F) (ON F E)
            (ON E H)))
)
