(define (problem BLOCKS-11-1)
(:domain BLOCKS)
(:objects B - block C - block E - block A - block H - block K - block I - block G - block D - block F - block J - block)
(:INIT ( and (CLEAR J) (CLEAR F) (CLEAR D) (CLEAR G) (ONTABLE I) (ONTABLE K)
 (ONTABLE H) (ONTABLE A) (ON J I) (ON F E) (ON E K) (ON D C) (ON C H) (ON G B)
 (ON B A) (HANDEMPTY)) )
(:goal (AND (ON B D) (ON D J) (ON J K) (ON K H) (ON H A) (ON A C) (ON C F)
            (ON F G) (ON G I) (ON I E)))
)
