(define (problem BLOCKS-11-0)
(:domain BLOCKS)
(:objects F - block A - block K - block H - block G - block E - block D - block I - block C - block J - block B - block)
(:INIT ( and (CLEAR B) (CLEAR J) (CLEAR C) (ONTABLE I) (ONTABLE D) (ONTABLE E)
 (ON B G) (ON G H) (ON H K) (ON K A) (ON A F) (ON F I) (ON J D) (ON C E)
 (HANDEMPTY)) )
(:goal (AND (ON A J) (ON J D) (ON D B) (ON B H) (ON H K) (ON K I) (ON I F)
            (ON F E) (ON E G) (ON G C)))
)
